FROM nginx:latest
RUN rm -fv /usr/share/nginx/html/index.html && \
touch /usr/share/nginx/html/index.html && \
echo '<html> \
<head> \
Hey, Netology \
</head> \
<body> \
<h1>I’m DevOps Engineer!</h1> \
</body> \
</html>' > /usr/share/nginx/html/index.html
